strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1

podSecurityContext:
 seccompProfile:
    type: Localhost
    localhostProfile: infra-seccomp.json

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  runAsUser: 1000

volumeMounts: []

volumes:
  - name: token-vol
    projected:
      sources:
        - serviceAccountToken:
            audience: api
            expirationSeconds: 600
            path: token