apiVersion: v1
kind: Service
metadata:
  name: {{ include "discourse.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "discourse.labels" . | nindent 4 }}
    {{- with .Values.podLabels }}
    {{- toYaml . | nindent 4}}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "discourse.selectorLabels" . | nindent 4 }}
