replicaCount: 1

image:
  repository: swr.cn-north-4.myhuaweicloud.com/opensourceway/lightrag
  tag: "v1.4.9.7"

service:
  type: ClusterIP
  port: 9621
  targetPort: 9621

resources:
  limits:
    cpu: "2"
    memory: 16Gi
  requests:
    cpu: "2"
    memory: 8Gi

persistence:
  enabled: true
  accessModes: ReadWriteMany
  storageClass: sfsturbo-subpath-sc
  ragStorage:
    size: 50Gi
  inputs:
    size: 30Gi

secretPath: secrets/data/mindspore/lightrag
