{{- if and .Values.ingress.enabled .Values.ingress.tlsSecrets.enabled }}
{{- with .Values.ingress.tlsSecrets }}
---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace.name }}
spec:
  name: {{ .name }}
  keysMap:
    ca.crt:
      key: {{ .certKey }}
      path: {{ .path }}
    tls.crt:
      key: {{ .certKey }}
      path: {{ .path }}
    tls.key:
      key: {{ .keyKey }}
      path: {{ .path }}
{{- end }}
{{- end }}
{{- range .Values.secret }}
---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace.name }}
spec:
  name: {{ .name }}
  keysMap:
  {{- $currentSecret := . }}
  {{- range $key, $val := .keysMap }}
    {{ $key }}:
      key: {{ $val }}
      path: {{ $currentSecret.path }}
  {{- end }}
{{- end }}