{{- range $index, $item := .Values.cronjobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: api-autotest-cronjob-{{ printf "%02d" (add $index 1) }}
spec:
  suspend: {{ $item.suspend }}
  schedule: {{ $item.schedule | quote }}
  concurrencyPolicy: {{ $item.concurrencyPolicy }}
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            {{- toYaml $.Values.podAnnotations | nindent 12 }}
            {{- toYaml $item.annotations | nindent 12 }}
        spec:
          imagePullSecrets:
            {{- toYaml $.Values.imagePullSecrets | nindent 12}}
          serviceAccount: {{ $.Values.serviceAccount.name }}
          automountServiceAccountToken: false
          securityContext:
            seccompProfile:
              type: Localhost
              localhostProfile: infra-seccomp.json
          restartPolicy: {{ $item.restartPolicy }}
          containers:
            - name: api-autotest
              {{- with $.Values.image }}
              image: "{{ .repository }}:{{ .tag }}"
              imagePullPolicy: {{ .pullPolicy }}
              {{- end }}
              env:
                - name: TZ
                  value: Asia/Shanghai
              securityContext:
                allowPrivilegeEscalation: false
                runAsUser: 1000
                readOnlyRootFilesystem: false
                capabilities:
                  drop:
                    - ALL
              resources:
                {{- toYaml $item.resources | nindent 16 }}
              volumeMounts:
                - name: volume-data
                  mountPath: /app/check/report
          volumes:
          - name: token-vol
            projected:
              sources:
              - serviceAccountToken:
                  audience: api
                  expirationSeconds: 600
                  path: token
          - name: volume-data
            persistentVolumeClaim:
              claimName: autotest-pvc-{{ printf "%02d" (add $index 1) }}
{{- end }}