{{- with .Values.pvc }}
{{- if .enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  accessModes:
    - {{ .accessModes }}
  resources:
    requests:
      storage: {{ .storage }}
  storageClassName: {{ .storageClassName }}
  volumeMode: {{ .volumeMode }}
  {{- if .volumeName }}
  volumeName: {{ .volumeName }}
  {{- end }}
{{- end }}
{{- end }}