# chartVersion: v1.0.5
global:
  appName: docs
namespace:
  enabled: false
  name: openubmc
replicaCount: 3
image:
  repository: swr.cn-north-4.myhuaweicloud.com/openubmc/openubmc-prod-docs
  tag: "main-19588b"
  pullPolicy: IfNotPresent
  pullSecret: huawei-swr-image-pull-secret
initContainers:
  - command:
      - /bin/bash
      - -c
      - chmod 0700 /etc/nginx/cert/; chown -R 1000:1000 /etc/nginx/cert/; chmod g-s /etc/nginx/cert/; ls -ld /etc/nginx/cert/
    image: swr.cn-north-4.myhuaweicloud.com/openubmc/openeuler:22.03-lts-sp3
    imagePullPolicy: IfNotPresent
    name: init-openeuler
podLabels:
  app: docs
podAnnotations:
  traffic.sidecar.istio.io/excludeOutboundIPRanges: 0.0.0.0/0
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/agent-inject-perms-server.crt: "0400"
  vault.hashicorp.com/agent-inject-perms-server.key: "0400"
  vault.hashicorp.com/agent-inject-perms-abc.txt: "0400"
  vault.hashicorp.com/agent-inject-perms-dhparam.pem: "0400"
  vault.hashicorp.com/agent-run-as-user: "1000"
  vault.hashicorp.com/agent-run-as-group: "1000"
  vault.hashicorp.com/secret-volume-path: "/etc/nginx/cert/"
  vault.hashicorp.com/agent-inject-secret-server.crt: "internal/data/openubmc/openubmc-website"
  vault.hashicorp.com/agent-inject-template-server.crt: |
    {{- with secret "internal/data/openubmc/openubmc-website" -}}
    {{ .Data.data.ServerCrt }}
    {{- end }}
  vault.hashicorp.com/agent-inject-secret-server.key: "internal/data/openubmc/openubmc-website"
  vault.hashicorp.com/agent-inject-template-server.key: |
    {{- with secret "internal/data/openubmc/openubmc-website" -}}
    {{ .Data.data.ServerKey }}
    {{- end }}
  vault.hashicorp.com/agent-inject-secret-abc.txt: "internal/data/openubmc/openubmc-website"
  vault.hashicorp.com/agent-inject-template-abc.txt: |
    {{- with secret "internal/data/openubmc/openubmc-website" -}}
    {{ .Data.data.certificatePassword }}
    {{- end }}
  vault.hashicorp.com/agent-inject-secret-dhparam.pem: "internal/data/openubmc/openubmc-website"
  vault.hashicorp.com/agent-inject-template-dhparam.pem: |
    {{- with secret "internal/data/openubmc/openubmc-website" -}}
    {{ .Data.data.dhparamPem }}
    {{- end }}
  vault.hashicorp.com/role: openubmc
  vault.hashicorp.com/agent-service-account-token-volume-name: "token-vol"
  vault.hashicorp.com/tls-skip-verify: "true"
  vault.hashicorp.com/agent-pre-populate-only: "true"
  vault.hashicorp.com/agent-inject-command-abc.txt: |
    if [ $(netstat -anlp | grep 8080| wc -l) -ge 1 ]; then rm -rf /etc/nginx/cert/*; else echo "service not running skip"; fi
  vault.hashicorp.com/agent-inject-command-server.crt: |
    if [ $(netstat -anlp | grep 8080| wc -l) -ge 1 ]; then rm -rf /etc/nginx/cert/*; else echo "service not running skip"; fi
  vault.hashicorp.com/agent-inject-command-server.key: |
    if [ $(netstat -anlp | grep 8080| wc -l) -ge 1 ]; then rm -rf /etc/nginx/cert/*; else echo "service not running skip"; fi
  vault.hashicorp.com/agent-inject-command-dhparam.pem: |
    if [ $(netstat -anlp | grep 8080| wc -l) -ge 1 ]; then rm -rf /etc/nginx/cert/*; else echo "service not running skip"; fi
  vault.hashicorp.com/template-static-secret-render-interval: 5s
  vault.hashicorp.com/agent-init-first: "true"
  vault.hashicorp.com/log-level: "warn"
env:
  - name: DET_URL
    value: https://www.openubmc.cn/docs/404.html
serviceAccount:
  create: false
  name: openubmc
  automount: false
# 资源限制
resources:
  requests:
    cpu: 500m
    memory: 500Mi
  limits:
    cpu: "1"
    memory: 1000Mi
livenessProbe:
  failureThreshold: 3
  initialDelaySeconds: 5
  periodSeconds: 20
  successThreshold: 1
  httpGet:
    scheme: HTTPS
    path: /zh/development/quick_start/explore_openubmc.html
    port: 8080
  timeoutSeconds: 5
readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 20
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3
  httpGet:
    scheme: HTTPS
    path: /zh/development/quick_start/explore_openubmc.html
    port: 8080
# Ingress配置
ingress:
  enabled: false
  # className: nginx
  # annotations:
  #   nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  # host: wwww.openubmc.cn
# Service配置
service:
  portName: tls-1
  type: ClusterIP
  port: 8080
  targetPort: 8080
secret:
  enable: false
  # name: openubmc-domain-tls
  # path: secrets/data/openubmc/openubmc-cn-tls
  # ca_crt_key: tls.cert
  # tls_crt_key: tls.cert
  # tls_key_key: tls.key
istio:
  enabled: false
  # nslabel:
  #   istio-injection: enabled
  # gateway: istio-system/istio-gateway-https
  # virtualService:
  #   host: www.openubmc.cn
  #   http:
  #     - route:
  #       - destination:
  #           host: docs-service.openubmc.svc.cluster.local
  #           port:
  #             number: 8080
  #       match:
  #       - uri:
  #           prefix: /
  #       rewrite:
  #         uri: /
  # tlsMode: SIMPLE
  # mtlsMode: DISABLE
