#chartVersion: 1.0.13
namespace:
  enabled: false
  name: mindspore-meetingserver
serviceAccount:
  create: true
  name: mindspore-meeting
strategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
  type: RollingUpdate
image:
  center:
    repository: swr.cn-north-4.myhuaweicloud.com/opensourceway/meeting/meeting-center
    tag: "main-e25083"
    imagePullPolicy: IfNotPresent
  platform:
    repository: "swr.cn-north-4.myhuaweicloud.com/opensourceway/meeting/meeting-platform"
    tag: "fix_mindspore-eaa947"
    imagePullPolicy: IfNotPresent
  server:
    repository: "swr.cn-north-4.myhuaweicloud.com/opensourceway/mindspore/mindspore-meeting-server"
    tag: "mindspore-website-ec39c7"
    imagePullPolicy: IfNotPresent
initContainer:
  image:
    repository: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler
    tag: "22.03-lts-sp3"
podAnnotations:
  vault.hashicorp.com/agent-init-first: "true"
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/agent-pre-populate-only: "true"
  vault.hashicorp.com/agent-run-as-group: "1000"
  vault.hashicorp.com/agent-run-as-user: "1000"
  vault.hashicorp.com/agent-service-account-token-volume-name: token-vol
  vault.hashicorp.com/role: mindspore-meeting-v2
  vault.hashicorp.com/tls-skip-verify: "true"
  vault.hashicorp.com/log-level: "warn"
  vault.hashicorp.com/agent-inject-perms-ca.pem: "0400"
  vault.hashicorp.com/agent-inject-perms-server.crt: "0400"
  vault.hashicorp.com/agent-inject-perms-server.key: "0400"
  vault.hashicorp.com/agent-inject-secret-ca.pem: internal/data/mindspore/mindspore-meeting-v2
  vault.hashicorp.com/agent-inject-secret-server.crt: internal/data/mindspore/mindspore-meeting-v2
  vault.hashicorp.com/agent-inject-secret-server.key: internal/data/mindspore/mindspore-meeting-v2
  vault.hashicorp.com/agent-inject-template-ca.pem: |
    {{- with secret "internal/data/mindspore/mindspore-meeting-v2" -}}
    {{ .Data.data.MysqlCA }}
    {{- end }}
  vault.hashicorp.com/agent-inject-template-server.crt: |
    {{- with secret "internal/data/mindspore/mindspore-meeting-v2" -}}
    {{ .Data.data.servercrt }}
    {{- end }}
  vault.hashicorp.com/agent-inject-template-server.key: |
    {{- with secret "internal/data/mindspore/mindspore-meeting-v2" -}}
    {{ .Data.data.serverkey }}
    {{- end }}
podSecurityContext:
  seccompProfile:
    type: Localhost
    localhostProfile: infra-seccomp.json
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  runAsUser: 1000
ingress:
  enabled: false
  name: api-ingress
  host: "api.mindspore.cn"
  serviceName: meeting-service
  serviceNumber: 8080
# 后端使用ingress路径转发时启用ingressNew
ingressNew:
  enabled: true
  name: api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /api$1
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  host: "api.mindspore.cn"
  path: /meetings(.*)
  pathType: ImplementationSpecific
  secretName: api-mindspore-tls
istio:
  enabled: false
  nslabel: {}
  # istio-injection: enabled
  gateway: "istio-system/istio-gateway-https"
  host: ""
  # vs:
  #   http:
  #     - match:
  #       - uri:
  #           prefix: /api-platform/
  #       rewrite:
  #         uri: /
  #       route:
  #       - destination:
  #           host: meeting-platform.meetingserver.svc.cluster.local
  #           port:
  #             number: 8080
  #     - match:
  #       - uri:
  #           prefix: /
  #       rewrite:
  #         uri: /
  #       route:
  #       - destination:
  #           host: meeting-center.meetingserver.svc.cluster.local
  #           port:
  #             number: 8080
  # dr:
  # - name: meeting-center
  #   serviceName: meeting-center
  #   portNumber: 8080
  #   tlsMode: SIMPLE
  # - name: meeting-platform
  #   serviceName: meeting-platform
  #   portNumber: 8080
  #   tlsMode: SIMPLE
  # pa:
  # - name: meeting-center
  #   mtlsMode: DISABLE
  #   label: 
  #     app: meeting-center
  # - name: meeting-platform
  #   mtlsMode: DISABLE
  #   label: 
  #     app: meeting-platform
meetingCenter:
  enabled: true
  name: meeting-center # 模板限制此项与Ingress关联
  replicas: 2
  podLabels:
    app: meeting-center
  resources:
    limits:
      cpu: "1"
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 500Mi
  service:
    type: ClusterIP
    annotations: {}
    ports:
      - name: http-port
        port: 8080
        protocol: TCP
        targetPort: 8080
  podAnnotations:
    vault.hashicorp.com/agent-inject-perms-config: "0400"
    vault.hashicorp.com/agent-inject-perms-secrets.yaml: "0400"
    vault.hashicorp.com/agent-inject-secret-config: internal/data/mindspore/mindspore-meeting-v2
    vault.hashicorp.com/agent-inject-secret-secrets.yaml: internal/data/mindspore/mindspore-meeting-v2
    vault.hashicorp.com/agent-inject-template-config: |
      {{- with secret "internal/data/mindspore/mindspore-meeting-v2" -}}
      {{ .Data.data.centerConfig }}
      {{- end }}
    vault.hashicorp.com/agent-inject-template-secrets.yaml: |
      {{- with secret "internal/data/mindspore/mindspore-meeting-v2" -}}
      {{ .Data.data.centerSecrets }}
      {{- end }}
meetingPlatform:
  enabled: true
  name: meeting-platform
  replicas: 2
  podLabels:
    app: meeting-platform
  resources:
    limits:
      cpu: "1"
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 500Mi
  service:
    ports:
      - name: http-port
        port: 8080
        protocol: TCP
        targetPort: 8080
    type: ClusterIP
  podAnnotations:
    vault.hashicorp.com/agent-inject-perms-config: "0400"
    vault.hashicorp.com/agent-inject-perms-secrets.yaml: "0400"
    vault.hashicorp.com/agent-inject-secret-config: internal/data/mindspore/mindspore-meeting-v2
    vault.hashicorp.com/agent-inject-secret-secrets.yaml: internal/data/mindspore/mindspore-meeting-v2
    vault.hashicorp.com/agent-inject-template-config: |
      {{- with secret "internal/data/mindspore/mindspore-meeting-v2" -}}
      {{ .Data.data.platformConfig }}
      {{- end }}
    vault.hashicorp.com/agent-inject-template-secrets.yaml: |
      {{- with secret "internal/data/mindspore/mindspore-meeting-v2" -}}
      {{ .Data.data.platformSecrets }}
      {{- end }}
meetingServer:
  enabled: false
  name: meetingserver-v2-deployment
  replicas: 2
  podLabels:
    app: meetingserver-v2
  env:
    - name: TZ
      value: Asia/Shanghai
    - name: CONFIG_PATH
      value: /vault/secrets/secrets.yaml
    - name: MYSQL_TLS_PEM_PATH
      value: /vault/secrets/ca.pem
    - name: TLS_CRT_PATH
      value: /vault/secrets/server.crt
    - name: TLS_KEY_PATH
      value: /vault/secrets/server.key
  resources:
    limits:
      cpu: "1"
      memory: 1000Mi
    requests:
      cpu: "1"
      memory: 1000Mi
  service:
    name: meeting-service
    ports:
      - name: http-port
        port: 8080
        protocol: TCP
        targetPort: 8080
    type: ClusterIP
  podAnnotations:
    vault.hashicorp.com/agent-inject-perms-secrets.yaml: "0400"
    vault.hashicorp.com/agent-inject-secret-secrets.yaml: internal/data/mindspore/mindspore-meeting-v2
    vault.hashicorp.com/agent-inject-template-secrets.yaml: |
      {{- with secret "internal/data/mindspore/mindspore-meeting-v2" -}}
      {{ .Data.data.config }}
      {{- end }}
secret:
  enabled: true
  name: api-mindspore-tls
  specKeysMap:
    ca.crt:
      path: secrets/data/mindspore/mindspore-cn-tls
      key: ca.cert
    tls.crt:
      path: secrets/data/mindspore/mindspore-cn-tls
      key: ca.cert
    tls.key:
      path: secrets/data/mindspore/mindspore-cn-tls
      key: ca.key
cronjobCommon:
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: false
    runAsUser: 1000
  env:
    - name: TZ
      value: Asia/Shanghai
    - name: CONFIG_PATH
      value: /vault/secrets/config
    - name: VAULT_PATH
      value: /vault/secrets/secrets.yaml
    - name: MYSQL_TLS_PEM_PATH
      value: /vault/secrets/ca.pem
    - name: TLS_CRT_PATH
      value: /vault/secrets/server.crt
    - name: TLS_KEY_PATH
      value: /vault/secrets/server.key
cronjobs:
  - enabled: true
    name: mindspore-handle-meeting
    labels:
      app: mindspore-handle-meeting
    concurrencyPolicy: Forbid
    schedule: "*/15 * * * *"
    suspend: false
    restartPolicy: OnFailure
    podAnnotations:
      vault.hashicorp.com/agent-inject-perms-config: "0400"
      vault.hashicorp.com/agent-inject-perms-secrets.yaml: "0400"
      vault.hashicorp.com/agent-inject-secret-config: internal/data/mindspore/mindspore-meeting-v2
      vault.hashicorp.com/agent-inject-secret-secrets.yaml: internal/data/mindspore/mindspore-meeting-v2
      vault.hashicorp.com/agent-inject-template-config: |
        {{- with secret "internal/data/mindspore/mindspore-meeting-v2" -}}
        {{ .Data.data.platformConfig }}
        {{- end }}
      vault.hashicorp.com/agent-inject-template-secrets.yaml: |
        {{- with secret "internal/data/mindspore/mindspore-meeting-v2" -}}
        {{ .Data.data.platformSecrets }}
        {{- end }}
    command:
      - /bin/sh
      - -c
      - |
        python3 manage.py handle_meeting
    image:
      repository: swr.cn-north-4.myhuaweicloud.com/opensourceway/meeting/meeting-platform
      tag: "fix_mindspore-eaa947"
      imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 500m
        memory: 500Mi
  - enabled: true
    name: mindspore-handle-recording
    labels:
      app: mindspore-handle-recording
    concurrencyPolicy: Forbid
    schedule: "30 * * * *"
    suspend: false
    restartPolicy: OnFailure
    podAnnotations:
      vault.hashicorp.com/agent-inject-perms-config: "0400"
      vault.hashicorp.com/agent-inject-perms-secrets.yaml: "0400"
      vault.hashicorp.com/agent-inject-secret-config: internal/data/mindspore/mindspore-meeting-v2
      vault.hashicorp.com/agent-inject-secret-secrets.yaml: internal/data/mindspore/mindspore-meeting-v2
      vault.hashicorp.com/agent-inject-template-config: |
        {{- with secret "internal/data/mindspore/mindspore-meeting-v2" -}}
        {{ .Data.data.platformConfig }}
        {{- end }}
      vault.hashicorp.com/agent-inject-template-secrets.yaml: |
        {{- with secret "internal/data/mindspore/mindspore-meeting-v2" -}}
        {{ .Data.data.platformSecrets }}
        {{- end }}
    command:
      - /bin/sh
      - -c
      - |
        python3 manage.py handle_recordings
    image:
      repository: swr.cn-north-4.myhuaweicloud.com/opensourceway/meeting/meeting-platform
      tag: "fix_mindspore-eaa947"
      imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 6
        memory: 1Gi
      requests:
        cpu: 6
        memory: 1Gi
