{{- if .Values.website.autoscale.enabled }}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Values.website.appName }}-autoscaler
  namespace: {{ .Values.namespace.name }}
spec:
  scaleTargetRef:
    name: {{ .Values.website.appName }}
  triggers:
  - metadata:
      desiredReplicas: {{ .Values.website.replicaCount | quote }}
      start: {{ .Values.website.autoscale.start | quote }}
      end: {{ .Values.website.autoscale.end | quote }}
      timezone: Asia/Shanghai
    type: cron
{{- end }}