{{- with .Values.meetingCenter }}
{{- if .enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  {{- with .deploymentLabels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{  .replicas }}
  {{- with $.Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- with  .podLabels }}
    matchLabels:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  template:
    metadata:
      {{- with  .podLabels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      annotations:
      {{- with $.Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with  .podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      automountServiceAccountToken: false
      {{- with $.Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - env:
        - name: TZ
          value: Asia/Shanghai
        - name: CONFIG_PATH
          value: /vault/secrets/config
        - name: VAULT_PATH
          value: /vault/secrets/secrets.yaml
        image: "{{ $.Values.image.center.repository }}:{{ $.Values.image.center.tag }}"
        imagePullPolicy: {{ $.Values.image.center.imagePullPolicy }}
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 30
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 5
        name: meeting-center
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 30
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 5
        resources: {{- toYaml  .resources | nindent 10 }}
        securityContext: {{- toYaml $.Values.securityContext | nindent 10 }}
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      - command:
        - /bin/bash
        - -c
        - chmod 0700 /vault/secrets/; chown -R 1000:1000 /vault/secrets/; chmod g-s /vault/secrets/;
          ls -ld /vault/secrets/
        image: "{{ $.Values.initContainer.image.repository }}:{{ $.Values.initContainer.image.tag }}"
        imagePullPolicy: IfNotPresent
        name: init-openeuler
      serviceAccount: {{ $.Values.serviceAccount.name }}
      serviceAccountName: {{ $.Values.serviceAccount.name }}
      volumes:
      - name: token-vol
        projected:
          sources:
          - serviceAccountToken:
              audience: api
              expirationSeconds: 600
              path: token
{{- end }}
{{- end }}
