namespace: om
autoscaling:
  enabled: false
serviceAccount:
  create: true
  name: om
imageRepository: swr.cn-north-4.myhuaweicloud.com/openubmc/om-collection
imagePullSecrets:
  - name: huawei-swr-image-pull-secret
podSecurityContext:
  seccompProfile:
    localhostProfile: infra-seccomp.json
    type: Localhost
podAnnotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/agent-run-as-group: "1001"
  vault.hashicorp.com/agent-run-as-user: "1001"
  vault.hashicorp.com/agent-service-account-token-volume-name: token-vol
  vault.hashicorp.com/role: om
  vault.hashicorp.com/template-static-secret-render-interval: 5s
  vault.hashicorp.com/tls-skip-verify: "true"
  vault.hashicorp.com/log-level: "warn"
deployments:
  - name: meeting
    enabled: true
    replicaCount: 1
    imageTag: meeting_1.5
    imagePullPolicy: IfNotPresent
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 0
        maxSurge: 1
    podAnnotations:
      vault.hashicorp.com/agent-inject-perms-config.ini: "0400"
      vault.hashicorp.com/agent-inject-secret-config.ini: internal/data/openubmc/om
      vault.hashicorp.com/agent-inject-template-config.ini: "{{- with secret \"internal/data/openubmc/om\" -}}  \n{{ .Data.data.Meeting }}\n{{- end }}\n"
      vault.hashicorp.com/secret-volume-path: /opt/config
    configPath: /opt/config
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      runAsUser: 1001
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 500m
        memory: 500Mi
    volumeMounts: {}
    volumes:
      - name: token-vol
        projected:
          sources:
            - serviceAccountToken:
                audience: api
                expirationSeconds: 600
                path: token
  - name: gitcode-user-info
    enabled: true
    replicaCount: 1
    imageTag: 0.6.52
    imagePullPolicy: IfNotPresent
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 0
        maxSurge: 1
    podAnnotations:
      vault.hashicorp.com/agent-inject-perms-config.ini: "0400"
      vault.hashicorp.com/agent-inject-secret-config.ini: internal/data/openubmc/om
      vault.hashicorp.com/agent-inject-template-config.ini: "{{- with secret \"internal/data/openubmc/om\" -}}  \n{{ .Data.data.GitcodeUserInfo }}\n{{- end }}\n"
      vault.hashicorp.com/secret-volume-path: /opt/config
    configPath: /opt/config
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      runAsUser: 1001
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 500m
        memory: 500Mi
    volumeMounts: {}
    volumes:
      - name: token-vol
        projected:
          sources:
            - serviceAccountToken:
                audience: api
                expirationSeconds: 600
                path: token
  - name: git-commit-log
    enabled: true
    replicaCount: 1
    imageTag: 0.6.54
    imagePullPolicy: IfNotPresent
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 0
        maxSurge: 1
    podAnnotations:
      vault.hashicorp.com/agent-inject-perms-config.ini: "0400"
      vault.hashicorp.com/agent-inject-secret-config.ini: internal/data/openubmc/om
      vault.hashicorp.com/agent-inject-template-config.ini: "{{- with secret \"internal/data/openubmc/om\" -}}  \n{{ .Data.data.GitCommitLog }}\n{{- end }}\n"
      vault.hashicorp.com/secret-volume-path: /opt/config
    configPath: /opt/config
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      runAsUser: 1001
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 500m
        memory: 500Mi
    volumeMounts:
      - mountPath: /mnt
        name: data
        subPath: git-commit-log
    volumes:
      - name: token-vol
        projected:
          sources:
            - serviceAccountToken:
                audience: api
                expirationSeconds: 600
                path: token
      - name: data
        persistentVolumeClaim:
          claimName: pvc-om-sfs-turbo
  - name: cla
    enabled: true
    replicaCount: 1
    imageTag: 0.6.52
    imagePullPolicy: IfNotPresent
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 0
        maxSurge: 1
    podAnnotations:
      vault.hashicorp.com/agent-inject-perms-config.ini: "0400"
      vault.hashicorp.com/agent-inject-secret-config.ini: internal/data/openubmc/om
      vault.hashicorp.com/agent-inject-template-config.ini: "{{- with secret \"internal/data/openubmc/om\" -}}  \n{{ .Data.data.Cla }}\n{{- end }}\n"
      vault.hashicorp.com/secret-volume-path: /opt/config
    configPath: /opt/config
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      runAsUser: 1001
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 500m
        memory: 500Mi
    volumeMounts: {}
    volumes:
      - name: token-vol
        projected:
          sources:
            - serviceAccountToken:
                audience: api
                expirationSeconds: 600
                path: token
collectData:
  enabled: true
  name: collect-data
  image:
    repository: swr.cn-north-4.myhuaweicloud.com/openubmc/om-collection
    tag: openubmc_2025.7.17
  replicaCount: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  labels:
    app: collect-data
  podAnnotations: {}
  imagePullSecrets:
    - name: huawei-swr-image-pull-secret
  podSecurityContext:
    seccompProfile:
      localhostProfile: infra-seccomp.json
      type: Localhost
  config:
    path: /opt/config
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    runAsUser: 1001
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 500m
      memory: 500Mi
  volumeMounts:
    - mountPath: /var/lib/om/config.ini
      name: om-collect-secrets-volume
      subPath: credentials_cfg
  volumes:
    - name: om-collect-secrets-volume
      secret:
        secretName: collect-data
secret:
  enabled: true
  name: collect-data
  path: secrets/data/openubmc/om
  keysMaps:
    credentials_cfg:
      key: openubmc_collect_data_credentials.cfg
