{{- with .Values.meetingPlatform }}
{{- if .enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  type: {{ .service.type }}
  selector:
    {{- toYaml .podLabels | nindent 4 }}
  ports:
  {{- .service.ports | toYaml | nindent 2 }}
{{- end }}
{{- end }}
