apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name | quote }}
  labels:
  {{- with .Values.pvc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
  {{- toYaml .Values.pvc.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage | quote }}
  storageClassName: {{.Values.pvc.storageClassName | quote }}
  volumeMode: {{ .Values.pvc.volumeMode | quote }}
