{{- if .Values.autoscale.enabled }}
{{- range .Values.deployments }}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .name }}-autoscaler
  namespace: {{ $.Values.namespace.name }}
spec:
  scaleTargetRef:
    name: {{ .name }}
  triggers:
  - metadata:
      desiredReplicas: {{ .replicas | quote }}
      start: {{ $.Values.autoscale.start | quote }}
      end: {{ $.Values.autoscale.end | quote }}
      timezone: Asia/Shanghai
    type: cron
{{- end }}
{{- end }}