{{- $secret := .Values.secret }}
{{- with $secret }}
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: {{ .name }}
spec:
  keysMap:
  {{- range $key, $val := .keysMap }}
    {{ $key }}:
      key: {{ $val }}
      path: {{ $secret.path }}
  {{- end }}
  name: {{ $secret.name }}
{{- end }}
