{{- if .Values.database.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-volume" .Values.database.name }}
  namespace: {{ .Values.global.namespace }}
  annotations:
    everest.io/disk-volume-type: SSD
spec:
  accessModes:
{{- range .Values.database.pvc.accessModes }}
    - {{ . }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.database.pvc.size }}
  storageClassName: {{ .Values.database.pvc.storageClassName }}
{{- end }}