apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  name: {{ .Values.secret.name }}
  keysMap:
    {{- with .Values.secret.secretdefine }}
    {{- toYaml . | nindent 4 }}
    {{- end }}