#chartVersion: 1.0.7
deployment:
  replicaCount: 1
  labels:
    app: control-etherpad-v2
  strategy:
    type: Recreate
  image:
    repository: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/etherpad
    pullPolicy: IfNotPresent
    tag: "main-383f61"
  imagePullSecrets:
    - name: huawei-swr-image-pull-secret
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-inject-perms-apikey.txt: "0400"
    vault.hashicorp.com/agent-inject-perms-credentials.json: "0400"
    vault.hashicorp.com/agent-inject-secret-apikey.txt: internal/data/mindspore/etherpad
    vault.hashicorp.com/agent-inject-secret-credentials.json: internal/data/mindspore/etherpad
    vault.hashicorp.com/agent-inject-template-apikey.txt: "{{- with secret \"internal/data/mindspore/etherpad\" -}}  \n{{ .Data.data.apikey }}\n{{- end }}\n"
    vault.hashicorp.com/agent-inject-template-credentials.json: "{{- with secret \"internal/data/mindspore/etherpad\" -}}  \n{{ .Data.data.config }}\n{{- end }}\n"
    vault.hashicorp.com/agent-pre-populate-only: "true"
    vault.hashicorp.com/agent-run-as-group: "5001"
    vault.hashicorp.com/agent-run-as-user: "5001"
    vault.hashicorp.com/agent-service-account-token-volume-name: token-vol
    vault.hashicorp.com/log-level: warn
    vault.hashicorp.com/role: etherpad
    vault.hashicorp.com/tls-skip-verify: "true"
  containerName: etherpad-lite
  ports:
    - containerPort: 9001
      name: http
      protocol: TCP
# This is to override the chart name.
nameOverride: ""
fullnameOverride: "mindspore-etherpad"
namespace: mindspore-etherpad
serviceAccount:
  create: true
  name: etherpad
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
secretDefinitions:
  etherpad-tls:
    enabled: true
    keysMap:
      ca.crt:
        key: ca.cert
        path: secrets/data/mindspore/mindspore-cn-tls
      tls.crt:
        key: ca.cert
        path: secrets/data/mindspore/mindspore-cn-tls
      tls.key:
        key: ca.key
        path: secrets/data/mindspore/mindspore-cn-tls
# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  ports:
    - name: ether-http
      port: 9001
      protocol: TCP
      targetPort: 9001
  type: ClusterIP
# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-credentials: "false"
    nginx.ingress.kubernetes.io/server-snippet: |
      location ^~ /admin {
        deny all;
      }
      location ^~ /stats {
        deny all;
      }
  hosts:
    - host: etherpad.mindspore.cn
      paths:
        - path: /
          pathType: Prefix
          portNumber: 9001
  tlsHosts:
    - host: etherpad.mindspore.cn
      secretsName: etherpad-mindspore-v2-tls
istio:
  enabled: false
  nslabel: {}
  # istio-injection: enabled
  # gateway: "istio-system/istio-gateway-https"
  # host: etherpad.opengaus.org
  # virtualService:
  #   routes:
  #     - destinations:
  #         - host: ""
  #       match:
  #       - uri:
  #           prefix: /
  # tls:
  #   mode: DISABLE
  # mtls:
  #   mode: DISABLE
resources:
  limits:
    cpu: "2"
    memory: 2000Mi
  requests:
    cpu: "2"
    memory: 2000Mi
pvc:
  ether-data-vol-v2:
    enabled: true
    annotations: {}
    # everest.io/disk-volume-type: SSD
    labels: {}
    accessModes:
      - ReadWriteOnce
    storage: 1Gi
    storageClassName: csi-disk-sas
    volumeName: "pvc-fb7e2105-ab4a-47b3-8acb-e932e57ad439"
    volumeMode: Filesystem
  etherpad-plugin-vol:
    enabled: false
    annotations:
      everest.io/disk-volume-type: SSD
    labels:
      failure-domain.beta.kubernetes.io/region: ap-southeast-1
      failure-domain.beta.kubernetes.io/zone: ap-southeast-1c
    accessModes:
      - ReadWriteOnce
    storage: 1Gi
    storageClassName: csi-disk
    volumeName: ""
    volumeMode: Filesystem
# Additional volumes on the output Deployment definition.
volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: ether-data-vol-v2
  # - name: plugin-volume
  #   persistentVolumeClaim:
  #     claimName: etherpad-plugin-vol
  - name: token-vol
    projected:
      sources:
        - serviceAccountToken:
            audience: api
            expirationSeconds: 600
            path: token
# Additional volumeMounts on the output Deployment definition.
volumeMounts:
  - mountPath: /opt/etherpad-lite/var
    name: data-volume
# - mountPath: /opt/etherpad-lite/plugin_packages
#   name: plugin-volume
