{{- if .Values.secret.enabled }}
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
spec:
 name: {{ .Values.secret.name }}
 keysMap:
   ca.crt:
     path: {{ .Values.secret.path }}
     key: {{ .Values.secret.tls_crt_key }}
   tls.crt:
     path: {{ .Values.secret.path }}
     key: {{ .Values.secret.tls_crt_key }}
   tls.key:
     path: {{ .Values.secret.path }}
     key: {{ .Values.secret.tls_key_key }}
{{- end }}