apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mailweb.name }}
  {{- with .Values.mailweb.deploymentLabels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.mailweb.replicas }}
  {{- with .Values.mailweb.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- with .Values.mailweb.podLabels }}
    matchLabels:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  template:
    metadata:
      {{- with .Values.mailweb.podLabels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      automountServiceAccountToken: false
      {{- if .Values.mailweb.nodeSelector }}
      nodeSelector: {{- toYaml .Values.mailweb.nodeSelector | nindent 8 }}
      {{- end }}     
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - env:
        {{- range .Values.mailweb.env.secretRef.keys }}
        - name: {{ .name }}
          valueFrom:
            secretKeyRef:
              key: {{ .key }}
              name: {{ $.Values.mailweb.env.secretRef.name }}
        {{- end }}
        {{- range .Values.mailweb.env.plainValues }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        - name: MAILMAN_REST_URL
          value: "http://{{.Values.mailcore.service.name}}.{{.Values.namespace.name}}.svc.cluster.local:8001"
        - name: MAILMAN_HOST_IP
          value: "{{.Values.mailcore.service.name}}.{{.Values.namespace.name}}.svc.cluster.local"
        image: {{ .Values.mailweb.image.repository }}:{{ .Values.mailweb.image.tag }}
        imagePullPolicy: {{ .Values.mailweb.image.imagePullPolicy }}
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 8000
          timeoutSeconds: 1
        name: {{ .Values.mailweb.name }}
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 8000
          timeoutSeconds: 1
        resources: {{- toYaml .Values.mailweb.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /opt/mailman-web-static
          name: mailman-web-volume
      - image: {{ .Values.nginxWeb.image.repository }}:{{ .Values.nginxWeb.image.tag }}
        imagePullPolicy: {{ .Values.nginxWeb.image.imagePullPolicy }}
        name: nginx-web
        resources: {{- toYaml .Values.nginxWeb.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: mailman-nginx-configmap-volume
          subPath: nginx.conf
        - mountPath: /etc/nginx/conf.d/default.conf
          name: mailman-nginx-configmap-volume
          subPath: default.conf
        - mountPath: /opt/mailman-web-static
          name: mailman-web-volume
      volumes:
      - emptyDir: {}
        name: mailman-web-volume
      - configMap:
          defaultMode: 420
          name: {{ .Values.nginxWeb.configmapName }}
        name: mailman-nginx-configmap-volume
