apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oneid-workbench.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  {{- with .Values.deploymentLabels }}
  labels:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "oneid-workbench.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "oneid-workbench.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        {{- toYaml .Values.initContainers | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.env }}
          env:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            httpGet:
              {{- toYaml .Values.healthCheck | nindent 14 }}
            timeoutSeconds: 5
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            httpGet:
              {{- toYaml .Values.healthCheck | nindent 14 }}
            timeoutSeconds: 5
          ports:
            - containerPort: {{ (index .Values.service.ports 0).targetPort }}
              name: {{ .Chart.Name }}
        - name: daprd  # Dapr 边车容器（必须挂载）
          image: "{{ .Values.daprd.image.repository }}:{{ .Values.daprd.image.tag }}"
          command:
          - /daprd
          args:                  
            - "--app-id"
            - "{{ include "oneid-workbench.fullname" . }}"            
            - "--app-port"            
            - "{{ (index .Values.service.ports 0).targetPort }}"
            - "--resources-path"
            - "/vault/secrets"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
