{{- if .Values.autoscale.enabled }}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "etherpad.fullname" . }}-deployment-autoscaler
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    name: {{ include "etherpad.fullname" . }}-deployment
  triggers:
  - metadata:
      desiredReplicas: {{ .Values.deployment.replicaCount | quote }}
      start: {{ .Values.autoscale.start | quote }}
      end: {{ .Values.autoscale.end | quote }}
      timezone: Asia/Shanghai
    type: cron
{{- end }}