apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.server.name }}-statefulset
  labels:
    {{- include "unifiedbus.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.server.statefulset.replicaCount }}
  {{- with .Values.server.statefulset.updateStrategy }}
  strategy: 
    {{- toYaml . | nindent 4 }}
  {{- end }}
  serviceName: {{ .Values.server.name }}-service
  selector:
    matchLabels:
      {{- with .Values.server.podLabels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  template:
    metadata:
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- toYaml .Values.server.podAnnotations | nindent 8 }}
      labels:
        {{- with .Values.server.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.server.name }}
          {{- with .Values.server.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          {{- with .Values.server.args }}
          args:
          {{- toYaml . | nindent 12}}
          {{- end }}
          {{- with .Values.server.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.server.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.server.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.server.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.server.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
