{{- if .Values.tls.enable }}
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: {{ .Values.community.name }}-tls
  namespace: {{ .Values.namespace.name }}
spec:
 name: {{ .Values.community.name }}-tls
 keysMap:
   ca.crt:
     path: {{ .Values.tls.secret.path }}
     key: {{ .Values.tls.secret.ca }}
   tls.crt:
     path: {{ .Values.tls.secret.path }}
     key: {{ .Values.tls.secret.ca }}
   tls.key:
     path: {{ .Values.tls.secret.path }}
     key: {{ .Values.tls.secret.key }}
{{- end }}