{{- if .Values.secret.enabled }}
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: {{ .Values.secret.name}}
  namespace: {{ .Values.namespace }}
spec:
  keysMap:
  {{- range $keyname, $values := .Values.secret.keysMaps }}
    {{ $keyname }}:
      key: {{ $values.key }}
      path: {{ $.Values.secret.path }}
  {{- end }}
  name: {{ .Values.secret.name}}
{{- end }}
