{{- if .Values.secret.enabled }}
---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
spec:
  name: {{ .Values.secret.name }}
  keysMap:
  {{- range $key, $val := .Values.secret.keysMap }}
    {{ $key }}:
      key: {{ $val }}
      path: {{ $.Values.secret.path }}
  {{- end }}
{{- end }}
