# chartVersion: v2.0.6
namespace:
  enabled: false
  name: robot
serviceAccount:
  create: true
  name: robot
deploymentLabels: {}
autoscale:
  enabled: false
podAnnotations:
  # traffic.sidecar.istio.io/excludeOutboundIPRanges: 0.0.0.0/0 # 开启istio时添加该行
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/agent-init-first: "true"
  vault.hashicorp.com/agent-pre-populate-only: "true"
  vault.hashicorp.com/agent-service-account-token-volume-name: token-vol
  vault.hashicorp.com/agent-run-as-user: "1000"
  vault.hashicorp.com/agent-run-as-group: "1000"
  vault.hashicorp.com/role: robot
  vault.hashicorp.com/tls-skip-verify: "true"
  vault.hashicorp.com/log-level: "warn"
istio:
  enabled: false
  nslabel: {}
ingress:
  host: "hook-delivery.hpckit.osinfra.cn"
  backends:
    - name: robot-universal-hook-delivery
      port: 8888
      path: /gitcode-hook
      pathType: Prefix
secret:
  enabled: true
  name: "tls-secret"
  path: "secrets/data/hpckit/hpckit-osinfra-cn-tls"
  crtKey: "server.cert"
  keyKey: "server.key"
imagePullSecrets:
  - name: huawei-swr-instance-image-pull-secret
podSecurityContext:
  seccompProfile:
    localhostProfile: infra-seccomp.json
    type: Localhost
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  runAsUser: 1000
initContainers:
  - command:
      - /bin/bash
      - -c
      - chmod 0700 /vault/secrets; chown -R 1000:1000 /vault/secrets; chmod g-s /vault/secrets; ls -ld /vault/secrets
    image: 'opensourceways-w5peto.swr-pro.myhuaweicloud.com/opensourceways/openeuler:22.03-lts-sp3'
    imagePullPolicy: IfNotPresent
    name: init-openeuler
readinessProbe: # 默认值
  failureThreshold: 3
  httpGet:
    path: /
    port: 8888
    scheme: HTTP
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
livenessProbe: # 默认值
  failureThreshold: 3
  httpGet:
    path: /
    port: 8888
    scheme: HTTP
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
deployments:
  # hookDelivery robot 必须填写为第一个数组元素
  - name: robot-universal-hook-delivery
    replicas: 2
    strategy:
      rollingUpdate:
        maxSurge: 2
        maxUnavailable: 0
      type: RollingUpdate
    labels:
      app: robot-universal-hook-delivery
    podAnnotations:
      vault.hashicorp.com/agent-inject-perms-config: "0400"
      vault.hashicorp.com/agent-inject-perms-gitcode-secret: "0400"
      vault.hashicorp.com/agent-inject-secret-config: internal/data/hpckit/robot
      vault.hashicorp.com/agent-inject-secret-gitcode-secret: internal/data/hpckit/robot
      vault.hashicorp.com/agent-inject-template-config: "{{- with secret \"internal/data/hpckit/robot\" -}}  \n{{ .Data.data.deliveryConfig }}\n{{- end }}\n"
      vault.hashicorp.com/agent-inject-template-gitcode-secret: "{{- with secret \"internal/data/hpckit/robot\" -}}  \n{{ .Data.data.deliverySecrets }}\n{{- end }}\n"
    args:
      - --port=8888
      - --hmac-secret-file=/vault/secrets/gitcode-secret
      - --config-file=/vault/secrets/config
      - --handle-path=gitcode-hook
    image:
      repository: opensourceways-w5peto.swr-pro.myhuaweicloud.com/opensourceways/robot-universal-hook-delivery
      tag: "main-d443fa"
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
    volumeMounts: []
    volumes: []
    vaultVolume: create
    service:
      portName: http-port
      port: 8888
      targetPort: 8888
      type: ClusterIP
  - name: robot-universal-access
    replicas: 2
    strategy:
      rollingUpdate:
        maxSurge: 2
        maxUnavailable: 0
      type: RollingUpdate
    labels:
      app: robot-universal-access
    podAnnotations: ''
    args:
      - --port=8888
      - --config-file=/app/conf/config.yaml
      - --handle-path=gitcode-hook
    image:
      repository: opensourceways-w5peto.swr-pro.myhuaweicloud.com/opensourceways/robot-universal-access
      tag: "main-547279"
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
    volumeMounts:
      - mountPath: /app/conf/
        name: app-config
        readOnly: true
    volumes:
      - name: app-config
        configMap:
          name: configmap-access
    vaultVolume: ''
    service:
      portName: http-port
      port: 8888
      targetPort: 8888
      type: ClusterIP
  - name: robot-hook-dispatcher
    replicas: 1
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
      type: RollingUpdate
    labels:
      app: robot-hook-dispatcher
    podAnnotations:
      vault.hashicorp.com/agent-inject-perms-config: "0400"
      vault.hashicorp.com/agent-inject-secret-config: internal/data/hpckit/robot
      vault.hashicorp.com/agent-inject-template-config: "{{- with secret \"internal/data/hpckit/robot\" -}}  \n{{ .Data.data.dispatcher }}\n{{- end }}\n"
    args:
      - --port=8888
      - --config-file=/vault/secrets/config
    image:
      repository: opensourceways-w5peto.swr-pro.myhuaweicloud.com/opensourceways/robot-hook-dispatcher
      tag: "main-6bdcee"
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
    volumeMounts: []
    volumes: []
    vaultVolume: create
    service:
      portName: http-port
      port: 8888
      targetPort: 8888
      type: ClusterIP
  - name: robot-universal-repo-watcher
    replicas: 1
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
      type: RollingUpdate
    labels:
      app: robot-universal-repo-watcher
    podAnnotations:
      vault.hashicorp.com/agent-inject-perms-token: "0400"
      vault.hashicorp.com/agent-inject-secret-token: internal/data/hpckit/robot
      vault.hashicorp.com/agent-inject-template-token: "{{- with secret \"internal/data/hpckit/robot\" -}}  \n{{ .Data.data.token }}\n{{- end }}\n"
    args:
      - --port=8888
      - --handle-path=gitcode-hook
      - --config-file=/app/conf/config.yaml
      - --token-path=/vault/secrets/token
    image:
      repository: opensourceways-w5peto.swr-pro.myhuaweicloud.com/opensourceways/robot-universal-repo-watcher
      tag: "main-0226e6"
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
    volumeMounts:
      - mountPath: /app/conf/
        name: app-config
        readOnly: true
      - mountPath: /opt/app/repo
        name: config-app
    volumes:
      - name: app-config
        configMap:
          name: configmap-repo-watcher
      - name: config-app
        emptyDir: {}
    vaultVolume: create
    service:
      portName: http-port
      port: 8888
      targetPort: 8888
      type: ClusterIP
  - name: robot-universal-welcome
    replicas: 2
    strategy:
      rollingUpdate:
        maxSurge: 2
        maxUnavailable: 0
      type: RollingUpdate
    labels:
      app: robot-universal-welcome
    podAnnotations:
      vault.hashicorp.com/agent-inject-perms-token: "0400"
      vault.hashicorp.com/agent-inject-secret-token: internal/data/hpckit/robot
      vault.hashicorp.com/agent-inject-template-token: "{{- with secret \"internal/data/hpckit/robot\" -}}  \n{{ .Data.data.token }}\n{{- end }}\n"
    args:
      - --port=8888
      - --config-file=/app/conf/config.yaml
      - --handle-path=gitcode-hook
      - --token-path=/vault/secrets/token
    image:
      repository: opensourceways-w5peto.swr-pro.myhuaweicloud.com/opensourceways/robot-universal-welcome
      tag: "main-769044"
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
    volumeMounts:
      - mountPath: /app/conf/
        name: app-config
        readOnly: true
    volumes:
      - name: app-config
        configMap:
          name: configmap-welcome
    vaultVolume: create
    service:
      portName: http-port
      port: 8888
      targetPort: 8888
      type: ClusterIP
  - name: robot-universal-cla
    replicas: 2
    strategy:
      rollingUpdate:
        maxSurge: 2
        maxUnavailable: 0
      type: RollingUpdate
    labels:
      app: robot-universal-cla
    podAnnotations:
      vault.hashicorp.com/agent-inject-perms-token: "0400"
      vault.hashicorp.com/agent-inject-secret-token: internal/data/hpckit/robot
      vault.hashicorp.com/agent-inject-template-token: "{{- with secret \"internal/data/hpckit/robot\" -}}  \n{{ .Data.data.token }}\n{{- end }}\n"
    args:
      - --port=8888
      - --config-file=/app/conf/config.yaml
      - --handle-path=gitcode-hook
      - --token-path=/vault/secrets/token
    image:
      repository: opensourceways-w5peto.swr-pro.myhuaweicloud.com/opensourceway/robot-universal-cla
      tag: "v1.0.20260610110812"
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
    volumeMounts:
      - mountPath: /app/conf/
        name: app-config
        readOnly: true
    volumes:
      - name: app-config
        configMap:
          name: configmap-cla
    vaultVolume: create
    service:
      portName: http-port
      port: 8888
      targetPort: 8888
      type: ClusterIP
  - name: robot-universal-label
    replicas: 2
    strategy:
      rollingUpdate:
        maxSurge: 2
        maxUnavailable: 0
      type: RollingUpdate
    labels:
      app: robot-universal-label
    podAnnotations:
      vault.hashicorp.com/agent-inject-perms-token: "0400"
      vault.hashicorp.com/agent-inject-secret-token: internal/data/hpckit/robot
      vault.hashicorp.com/agent-inject-template-token: "{{- with secret \"internal/data/hpckit/robot\" -}}  \n{{ .Data.data.token }}\n{{- end }}\n"
    args:
      - --port=8888
      - --config-file=/app/conf/config.yaml
      - --handle-path=gitcode-hook
      - --token-path=/vault/secrets/token
    image:
      repository: opensourceways-w5peto.swr-pro.myhuaweicloud.com/opensourceway/robot-universal-label
      tag: "v1.0.20260604143352"
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
    volumeMounts:
      - mountPath: /app/conf/
        name: app-config
        readOnly: true
    volumes:
      - name: app-config
        configMap:
          name: configmap-label
    vaultVolume: create
    service:
      portName: http-port
      port: 8888
      targetPort: 8888
      type: ClusterIP
  - name: robot-universal-lifecycle
    replicas: 2
    strategy:
      rollingUpdate:
        maxSurge: 2
        maxUnavailable: 0
      type: RollingUpdate
    labels:
      app: robot-universal-lifecycle
    podAnnotations:
      vault.hashicorp.com/agent-inject-perms-token: "0400"
      vault.hashicorp.com/agent-inject-secret-token: internal/data/hpckit/robot
      vault.hashicorp.com/agent-inject-template-token: "{{- with secret \"internal/data/hpckit/robot\" -}}  \n{{ .Data.data.token }}\n{{- end }}\n"
    args:
      - --port=8888
      - --config-file=/app/conf/config.yaml
      - --handle-path=gitcode-hook
      - --token-path=/vault/secrets/token
    image:
      repository: opensourceways-w5peto.swr-pro.myhuaweicloud.com/opensourceways/robot-universal-lifecycle
      tag: "develop-lts-298f05"
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
    volumeMounts:
      - mountPath: /app/conf/
        name: app-config
        readOnly: true
    volumes:
      - name: app-config
        configMap:
          name: configmap-lifecycle
    vaultVolume: create
    service:
      portName: http-port
      port: 8888
      targetPort: 8888
      type: ClusterIP
  - name: robot-universal-review
    replicas: 2
    strategy:
      rollingUpdate:
        maxSurge: 2
        maxUnavailable: 0
      type: RollingUpdate
    labels:
      app: robot-universal-review
    podAnnotations:
      vault.hashicorp.com/agent-inject-perms-token: "0400"
      vault.hashicorp.com/agent-inject-secret-token: internal/data/hpckit/robot
      vault.hashicorp.com/agent-inject-template-token: "{{- with secret \"internal/data/hpckit/robot\" -}}  \n{{ .Data.data.token }}\n{{- end }}\n"
    args:
      - --port=8888
      - --config-file=/app/conf/config.yaml
      - --handle-path=gitcode-hook
      - --token-path=/vault/secrets/token
    image:
      repository: opensourceways-w5peto.swr-pro.myhuaweicloud.com/opensourceways/robot-universal-review
      tag: "develop-lts-339536"
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
    volumeMounts:
      - mountPath: /app/conf/
        name: app-config
        readOnly: true
    volumes:
      - name: app-config
        configMap:
          name: configmap-review
    vaultVolume: create
    service:
      portName: http-port
      port: 8888
      targetPort: 8888
      type: ClusterIP
