# chartVersion: v1.0.6
global:
  appName: boostkit-oneid-website
namespace:
  enabled: false
  name: boostkit-website
replicaCount: 2
image:
  repository: swr.cn-north-4.myhuaweicloud.com/boostkit-infra/boostkit-oneid-website
  tag: "test-boostkit-87a463"
  pullPolicy: IfNotPresent
  pullSecret: huawei-swr-image-pull-secret
deploymentLabels:
podLabels:
  app: boostkit-oneid-website
podSecurityContext:
  seccompProfile:
    type: Localhost
    localhostProfile: infra-seccomp.json
podAnnotations:
  # traffic.sidecar.istio.io/excludeOutboundIPRanges: 0.0.0.0/0
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/agent-inject-perms-server.crt: "0400"
  vault.hashicorp.com/agent-inject-perms-server.key: "0400"
  vault.hashicorp.com/agent-inject-perms-abc.txt: "0400"
  vault.hashicorp.com/agent-inject-perms-dhparam.pem: "0400"
  vault.hashicorp.com/agent-run-as-user: "1000"
  vault.hashicorp.com/agent-run-as-group: "1000"
  vault.hashicorp.com/secret-volume-path: "/etc/nginx/cert/"
  vault.hashicorp.com/agent-inject-secret-server.crt: "internal/data/boostkit/website"
  vault.hashicorp.com/agent-inject-template-server.crt: |
    {{- with secret "internal/data/boostkit/website" -}}
    {{ .Data.data.ServerCrt }}
    {{- end }}
  vault.hashicorp.com/agent-inject-secret-server.key: "internal/data/boostkit/website"
  vault.hashicorp.com/agent-inject-template-server.key: |
    {{- with secret "internal/data/boostkit/website" -}}
    {{ .Data.data.ServerKey }}
    {{- end }}
  vault.hashicorp.com/agent-inject-secret-abc.txt: "internal/data/boostkit/website"
  vault.hashicorp.com/agent-inject-template-abc.txt: |
    {{- with secret "internal/data/boostkit/website" -}}
    {{ .Data.data.certificatePassword }}
    {{- end }}
  vault.hashicorp.com/agent-inject-secret-dhparam.pem: "internal/data/boostkit/website"
  vault.hashicorp.com/agent-inject-template-dhparam.pem: |
    {{- with secret "internal/data/boostkit/website" -}}
    {{ .Data.data.dhparamPem }}
    {{- end }}
  vault.hashicorp.com/role: boostkit-website
  vault.hashicorp.com/agent-service-account-token-volume-name: "token-vol"
  vault.hashicorp.com/tls-skip-verify: "true"
  vault.hashicorp.com/agent-pre-populate-only: "true"
  vault.hashicorp.com/agent-inject-command-dhparam.pem: |
    if [ $(netstat -anlp | grep 8080| wc -l) -ge 1 ]; then rm -rf /etc/nginx/cert/*; else echo "service not running skip"; fi
  vault.hashicorp.com/template-static-secret-render-interval: 5s
  vault.hashicorp.com/agent-init-first: "true"
  vault.hashicorp.com/log-level: "warn"
env:
  - name: DET_URL
    value: https://id.boostkit.osinfra.cn
serviceAccount:
  create: false
  name: boostkit-website
  automount: false
# 资源限制
resources:
  requests:
    cpu: "100m"
    memory: 100Mi
# Ingress配置
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  host: id.boostkit.osinfra.cn
# Service配置
service:
  portName: http-port
  type: ClusterIP
  port: 8080
  targetPort: 8080
secret:
  enable: false
  name: boostkit-osinfra-cn-tls
  path: secrets/data/boostkit/boostkit-osinfra-cn-tls
  ca_crt_key: server_crt
  tls_crt_key: server_crt
  tls_key_key: server_key
istio:
  enabled: false
  nslabel: {}
  # istio-injection: enabled
  gateway: istio-system/istio-gateway-https
  virtualService:
    host: ""
    http:
      - route:
          - destination:
              host: ""
              port:
                number: 8080
        match:
          - uri:
              prefix: /
        rewrite:
          uri: /
  tlsMode: SIMPLE
  mtlsMode: DISABLE
