apiVersion: v1
kind: Service
metadata:
  name: {{ include "etherpad.fullname" . }}-service
  labels:
  {{- include "etherpad.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    {{- include "etherpad.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.service.ports | toYaml | nindent 2 }}
