{{- if .Values.secrets.enabled }}
---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: {{ .Values.secrets.name }}
spec:
  name: {{ .Values.secrets.name }}
  keysMap:
  {{- range $key, $val := .Values.secrets.keysMap }}
    {{ $key }}:
      key: {{ $val }}
      path: {{ $.Values.secrets.path }}
  {{- end }}
{{- end }}
