# 全局配置
global:
  appName: oneid-website
namespace:
  enabled: false
  name: unifiedbus
# 副本配置
replicaCount: 3
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1
revisionHistoryLimitCount: 10
# 镜像配置
image:
  repository: swr.cn-north-4.myhuaweicloud.com/unifiedbus/oneid-website-prod
  tag: "release-319712"
  pullPolicy: IfNotPresent
  pullSecret: huawei-swr-image-pull-secret
podLabels:
  app: oneid-website
podAnnotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/agent-inject-perms-server.crt: "0400"
  vault.hashicorp.com/agent-inject-perms-server.key: "0400"
  vault.hashicorp.com/agent-inject-perms-abc.txt: "0400"
  vault.hashicorp.com/agent-inject-perms-dhparam.pem: "0400"
  vault.hashicorp.com/agent-run-as-user: "1000"
  vault.hashicorp.com/agent-run-as-group: "1000"
  vault.hashicorp.com/secret-volume-path: "/etc/nginx/cert/"
  vault.hashicorp.com/agent-inject-secret-server.crt: "internal/data/unifiedbus/website-tls"
  vault.hashicorp.com/agent-inject-template-server.crt: |
    {{- with secret "internal/data/unifiedbus/website-tls" -}}
    {{ .Data.data.ServerCrt }}
    {{- end }}
  vault.hashicorp.com/agent-inject-secret-server.key: "internal/data/unifiedbus/website-tls"
  vault.hashicorp.com/agent-inject-template-server.key: |
    {{- with secret "internal/data/unifiedbus/website-tls" -}}
    {{ .Data.data.ServerKey }}
    {{- end }}
  vault.hashicorp.com/agent-inject-secret-abc.txt: "internal/data/unifiedbus/website-tls"
  vault.hashicorp.com/agent-inject-template-abc.txt: |
    {{- with secret "internal/data/unifiedbus/website-tls" -}}
    {{ .Data.data.certificatePassword }}
    {{- end }}
  vault.hashicorp.com/agent-inject-secret-dhparam.pem: "internal/data/unifiedbus/website-tls"
  vault.hashicorp.com/agent-inject-template-dhparam.pem: |
    {{- with secret "internal/data/unifiedbus/website-tls" -}}
    {{ .Data.data.dhparamPem }}
    {{- end }}
  vault.hashicorp.com/role: unifiedbus
  vault.hashicorp.com/agent-service-account-token-volume-name: "token-vol"
  vault.hashicorp.com/tls-skip-verify: "true"
  vault.hashicorp.com/agent-pre-populate-only: "true"
  vault.hashicorp.com/agent-init-first: "true"
  vault.hashicorp.com/agent-inject-command-abc.txt: |
    if [ $(netstat -anlp | grep 8080| wc -l) -ge 1 ]; then rm -rf /etc/nginx/cert/*; else echo "service not running skip"; fi
  vault.hashicorp.com/template-static-secret-render-interval: 5s
  vault.hashicorp.com/log-level: "warn"
env:
  - name: DET_URL
    value: https://id.unifiedbus.com/
initContainers:
  - command:
      - /bin/bash
      - -c
      - chmod 0700 /etc/nginx/cert/; chown -R 1000:1000 /etc/nginx/cert/; chmod g-s /etc/nginx/cert/; ls -ld /etc/nginx/cert/
    image: swr.cn-north-4.myhuaweicloud.com/unifiedbus/openeuler:22.03-lts-sp3
    imagePullPolicy: IfNotPresent
    name: init-openeuler
serviceAccount:
  create: false
  name: unifiedbus
  automount: false
# 资源限制
resources:
  requests:
    cpu: 1
    memory: 1Gi
  limits:
    cpu: 1
    memory: 1Gi
livenessProbe:
  failureThreshold: 3
  initialDelaySeconds: 30
  periodSeconds: 10
  successThreshold: 1
  httpGet:
    scheme: HTTPS
    path: /
    port: 8080
    httpHeaders:
      - name: "Host"
        value: "id.unifiedbus.com"
  timeoutSeconds: 10
readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 30
  periodSeconds: 10
  successThreshold: 1
  httpGet:
    scheme: HTTPS
    path: /
    port: 8080
    httpHeaders:
      - name: "Host"
        value: "id.unifiedbus.com"
  timeoutSeconds: 10
# Ingress配置
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/limit-rpm: "10000"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "1"
    nginx.ingress.kubernetes.io/server-snippet: |
      location ^~ /favicon.ico {
        return 404;
      }
  host: id.unifiedbus.com
# Service配置
service:
  portName: http-port
  type: ClusterIP
  port: 8080
  targetPort: 8080
secret:
  enable: false
  name: tls-secret
  path: secrets/data/unifiedbus/tls
  ca_crt_key: tls.cert
  tls_crt_key: tls.cert
  tls_key_key: tls.key
istio:
  enabled: false
