{{- with .Values.secret }}
{{- if .enabled }}
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: {{ .name }}
  labels:
  {{- include "robot.labels" $ | nindent 4 }}
spec:
  keysMap: 
    ca.crt:
      path: {{ .path }}
      key: {{ .crtKey }}
    tls.crt:
      path: {{ .path }}
      key: {{ .crtKey }}
    tls.key:
      path: {{ .path }}
      key: {{ .keyKey }}
  name: {{ .name}}
{{- end }}
{{- end }}
