{{- range $server := .Values.deployments }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $server.name }}-service
spec:
  ports:
  - name: {{ $server.service.portName }}
    port: {{ $server.service.port }}
    protocol: TCP
    targetPort: {{ $server.service.targetPort }}
  {{- with $server.labels }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  type: {{ $server.service.type }}
{{- end }}
