namespace: etherpad
deployment:
  replicaCount: 1
  # labels:
  #   virtual-kubelet.io/burst-to-cci: enforce
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  image:
    repository: swr.cn-north-4.myhuaweicloud.com/boostkit-infra/etherpad
    pullPolicy: IfNotPresent
    tag: "feature-5bf196"
  imagePullSecrets:
    - name: huawei-swr-image-pull-secret
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-inject-perms-apikey.txt: "0400"
    vault.hashicorp.com/agent-inject-perms-credentials.json: "0400"
    vault.hashicorp.com/agent-inject-secret-apikey.txt: internal/data/boostkit/etherpad
    vault.hashicorp.com/agent-inject-secret-credentials.json: internal/data/boostkit/etherpad
    vault.hashicorp.com/agent-inject-template-apikey.txt: "{{- with secret \"internal/data/boostkit/etherpad\" -}}  \n{{ .Data.data.apikey }}\n{{- end }}\n"
    vault.hashicorp.com/agent-inject-template-credentials.json: "{{- with secret \"internal/data/boostkit/etherpad\" -}}  \n{{ .Data.data.config }}\n{{- end }}\n"
    vault.hashicorp.com/agent-pre-populate-only: "true"
    vault.hashicorp.com/agent-run-as-group: "5001"
    vault.hashicorp.com/agent-run-as-user: "5001"
    vault.hashicorp.com/agent-service-account-token-volume-name: token-vol
    vault.hashicorp.com/log-level: warn
    vault.hashicorp.com/role: etherpad
    vault.hashicorp.com/tls-skip-verify: "true"
  containerName: etherpad-lite
  ports:
    - containerPort: 5001
      name: http
      protocol: TCP
# This is to override the chart name.
nameOverride: ""
fullnameOverride: "boostkit-etherpad"
serviceAccount:
  create: true
  name: etherpad
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
secretDefinitions:
  boostkit-domain-tls:
    enabled: true
    keysMap:
      ca.crt:
        key: server_crt
        path: secrets/data/boostkit/boostkit-osinfra-cn-tls
      tls.crt:
        key: server_crt
        path: secrets/data/boostkit/boostkit-osinfra-cn-tls
      tls.key:
        key: server_key
        path: secrets/data/boostkit/boostkit-osinfra-cn-tls
# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  ports:
    - name: ether-http
      port: 9001
      protocol: TCP
      targetPort: 9001
  type: ClusterIP
# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      location ^~ /admin {
        deny all;
      }
      location ^~ /stats {
        deny all;
      }
  hosts:
    - host: etherpad.boostkit.osinfra.cn
      paths:
        - path: /
          pathType: Prefix
          portNumber: 9001
  tlsHosts:
    - host: etherpad.boostkit.osinfra.cn
      secretsName: boostkit-domain-tls
istio:
  enabled: false
  nslabel: {}
  # istio-injection: enabled
  # gateway: "istio-system/istio-gateway-https"
  # host: etherpad.boostkit.osinfra.cn
  # virtualService:
  #   routes:
  #     - destinations:
  #         - host: ""
  #       match:
  #       - uri:
  #           prefix: /
  # tls:
  #   mode: DISABLE
  # mtls:
  #   mode: DISABLE
resources:
  requests:
    cpu: "50m"
    memory: 500Mi
pvc:
  etherpad-data-vol:
    enabled: true
    accessModes:
      - ReadWriteMany
    storage: 10Gi
    storageClassName: sfsturbo-subpath-sc
    volumeMode: Filesystem
# Additional volumes on the output Deployment definition.
volumes:
  - name: token-vol
    projected:
      sources:
        - serviceAccountToken:
            audience: api
            expirationSeconds: 600
            path: token
  - name: data-volume
    persistentVolumeClaim:
      claimName: etherpad-data-vol
# - name: plugin-volume
#   persistentVolumeClaim:
#     claimName: etherpad-plugin-vol

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
  - mountPath: /opt/etherpad-lite/var
    name: data-volume
# - mountPath: /opt/etherpad-lite/plugin_packages
#   name: plugin-volume
