{{- if .Values.oauth }}
{{- range $server := .Values.oauth }}
---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: {{ $server.secret.name }}
  namespace: {{ $.Values.namespace.name }}
spec:
 name: {{ $server.secret.name }}
 keysMap:
 {{- range $server.env }}
   {{ .value }}:
     path: {{ $server.secret.path }}
     key: {{ .value }}
{{- end }}
{{- end }}
{{- end }}