{{- if .Values.secretdefine }}
---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: {{ $.Values.nameOverride }}-secrets
  namespace: {{ .Values.namespace }}
spec:
  name: {{ $.Values.nameOverride }}-secrets
  keysMap:
    {{- range .Values.secretdefine.secret }}
    {{.key}}:
      path: {{ .path }}
      key: {{.key}}
    {{- end }}
{{- end }}