---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: {{ include "lightrag.fullname" . }}-env
spec:
  name: {{ include "lightrag.fullname" . }}-env
  keysMap:
    env:
      key: env
      path: {{ .Values.secretPath }}
