{{- with .Values.cronjob }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  suspend: {{ .suspend }}
  schedule: {{ .schedule | quote }}
  concurrencyPolicy: {{ .concurrencyPolicy }}
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            {{- toYaml .annotations | nindent 12 }}
        spec:
          {{- with $.Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12}}
          {{- end }}
          serviceAccount: {{ $.Values.serviceAccount.name }}
          automountServiceAccountToken: false
          {{- with $.Values.podSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: {{ .restartPolicy }}
          containers:
            - name: {{ .name }}
              {{- with .securityContext }}
              securityContext:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              args:
              - /vault/secrets/config.json
              env:
              - name: Tz
                value: Asia/shanghai
              image: "{{ .image.repository }}:{{ .image.tag }}"
              imagePullPolicy: {{ .image.pullPolicy }}
              {{- with .resources }}
              resources:
                {{- toYaml .resources | nindent 16 }}
              {{- end }}
              volumeMounts:
                {{- toYaml .volumeMounts | nindent 16 }}
          volumes:
            {{- toYaml .volumes | nindent 12 }}
{{- end }}