apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  {{- with .Values.deploymentLabels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: doc-search
  strategy:
    {{- toYaml .Values.strategy | nindent 4 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:                            
        app: doc-search
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      imagePullSecrets: {{- toYaml .Values.imagePullSecret | nindent 8 }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: false
      containers:
      - name: doc-search
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: APPLICATION_PATH
          value: {{ .Values.configPath }}
        {{- with .Values.env }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        securityContext:
          {{- toYaml .Values.containerSecurityContext | nindent 10 }}
        volumeMounts:
          {{- toYaml .Values.volumeMounts | nindent 10 }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
