# chartVersion: 1.0.10
namespace:
  enabled: false
  name: mail
istio:
  enabled: false
  nslabel: {}
  # istio-injection: enabled
  gateway: "istio-system/istio-gateway-https"
  exim4Annotation: {}
  mailcoreAnnotation: {}
  tls:
    mode: SIMPLE
  mtlsMode: DISABLE
  http: {}
affinity: {}
host: mailweb.mindspore.cn
ingress:
  enabled: true
  name: mailweb-ingress
  secretName: mindspore-mailweb-tls
mailcore:
  name: mailman-core
  podLabels:
    app: mail-suit-service
    component: mail-core-service
  replicas: 1
  nodeSelector: {}
  image:
    repository: swr.cn-north-4.myhuaweicloud.com/opensourceway/app-mailman/mailman-core-new-build
    tag: 0d995da03cd978a16d0730caa6d36846313bceb91740095397
    imagePullPolicy: IfNotPresent
  env:
    secretRef:
      name: mailman-secrets
      keys:
        - name: DATABASE_TYPE
          key: database_type
        - name: DATABASE_CLASS
          key: database_class
        - name: MAILMAN_REST_USER
          key: mailman_core_user
        - name: MAILMAN_REST_PASSWORD
          key: mailman_core_password
        - name: HYPERKITTY_API_KEY
          key: hyperkitty_api_key
        - name: EMAIL_HOST_USER
          key: exim4_credential_username
        - name: EMAIL_HOST_PASSWORD
          key: exim4_credential_password
        - name: MM_HOSTNAME
          key: mailcore_mm_hostname
        - name: MAILMAN_REST_PORT
          key: mailcore_rest_port
        - name: DATABASE_URL
          key: mailcore_database_url
        - name: MTA
          key: mailcore_mta
        - name: SMTP_PORT
          key: mailcore_smtp_port
  resources:
    limits:
      cpu: "4"
      memory: 4Gi
    requests:
      cpu: "4"
      memory: 4Gi
  pvc:
    name: config-vol
    accessMode: ReadWriteMany
    storage: 500Gi
    storageClass: csi-sfsturbo
  service:
    name: mailman-core-service
    type: ClusterIP
    ports:
      - name: core-service
        port: 8001
        protocol: TCP
        targetPort: 8001
      - name: core-service-2
        port: 8024
        protocol: TCP
        targetPort: 8024
exim4:
  name: mailman-exim4
  podLabels:
    app: mail-suit-service
    component: mail-exim4-service
  replicas: 1
  nodeSelector: {}
  image:
    repository: swr.cn-north-4.myhuaweicloud.com/opensourceway/app-mailman/mailman-exim-new-build
    tag: afc9ba498e609ffa2e3a529375b4951a301458491770102443
    imagePullPolicy: IfNotPresent
  nodeSelector: {}
  resources:
    limits:
      cpu: "4"
      memory: 2Gi
    requests:
      cpu: "2"
      memory: 1Gi
  configmapName: exim-configmap
  volumeMounts:
    - mountPath: /opt/mailman/
      name: mailman-core-data
    - mountPath: /var/log/exim/
      name: mailman-exim4-log
    - name: mailman-secrets
      mountPath: /etc/exim/passwd
      subPath: exim4_credential
    - name: mailman-cert-secrets
      mountPath: /etc/exim/exim.crt
      subPath: server_crt
    - name: mailman-cert-secrets
      mountPath: /etc/exim/exim.key
      subPath: server_key
    - name: mailman-secrets
      mountPath: /etc/exim/dkim/mindspore.key
      subPath: dkim_key
    - name: exim4-tls-secret
      mountPath: /etc/exim/ssl_pool/mindspore.cn.crt
      subPath: mindspore_cn_crt
    - name: exim4-tls-secret
      mountPath: /etc/exim/ssl_pool/mindspore.cn.key
      subPath: mindspore_cn_key
    - name: exim-config
      mountPath: /etc/exim/exim.conf
      subPath: exim_conf
  volumes:
    - name: mailman-core-data
      persistentVolumeClaim:
        claimName: config-vol
    - name: mailman-exim4-log
      persistentVolumeClaim:
        claimName: exim-log-data
    - name: mailman-secrets
      secret:
        secretName: mailman-secrets
    - name: mailman-cert-secrets
      secret:
        secretName: mailman-cert-secrets
    - name: exim4-tls-secret
      secret:
        secretName: mailman-tls-secrets
    - name: exim-config
      configMap:
        name: exim-configmap
  pvc:
    name: exim-log-data
    accessMode: ReadWriteOnce
    storage: 100Gi
    storageClass: csi-disk
  service:
    name: mailman-exim4-service
    elbId: 96d5b2cf-4e23-49b3-aa75-09e388dad123
    elbClass: union
    type: LoadBalancer
    ports:
      - port: 25
        name: exim4-port
        targetPort: 25
        protocol: TCP
      - port: 465
        name: exim4-port-2
        targetPort: 465
        protocol: TCP
mailweb:
  name: mailman-web
  podLabels:
    app: mail-suit-service
    component: mail-web-service
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  nodeSelector: {}
  image:
    repository: swr.cn-north-4.myhuaweicloud.com/opensourceway/app-mailman/mailman-web-new-build
    tag: b70fe4b2feb2d335fb591c975c54348d6a6f0d911740470898
    imagePullPolicy: Always
  env:
    secretRef:
      name: mailman-secrets
      keys:
        - name: DATABASE_TYPE
          key: database_type
        - name: HYPERKITTY_API_KEY
          key: hyperkitty_api_key
        - name: SECRET_KEY
          key: secret_key
        - name: MAILMAN_REST_USER
          key: mailman_core_user
        - name: MAILMAN_REST_PASSWORD
          key: mailman_core_password
        - name: MAILMAN_ADMIN_EMAIL
          key: mailman_admin_email
        - name: EMAIL_HOST_USER
          key: exim4_credential_username
        - name: EMAIL_HOST_PASSWORD
          key: exim4_credential_password
        #NOTE: this is the domain name that mailman web will serve
        - name: SERVE_FROM_DOMAIN
          key: mailweb_server_from_domain
        - name: SERVE_WEB_DOMAIN
          key: mailweb_server_web_domain
        - name: SMTP_HOST
          key: mailweb_smtp_host
        - name: SMTP_PORT
          key: mailweb_smtp_port
        - name: DJANGO_ALLOWED_HOSTS
          key: mailweb_django_allowed_hosts
        - name: POSTORIUS_TEMPLATE_BASE_URL
          key: mailweb_postorius_template_base_url
        - name: DATABASE_URL
          key: mailweb_database_url
        - name: redis_ip
          key: mailweb_redis_ip
        - name: redis_port
          key: mailweb_redis_port
        - name: redis_password
          key: mailweb_redis_password
        - name: XARMOR_APP_ID
          key: xarmor_app_id
        - name: XARMOR_APP_TOKEN
          key: xarmor_app_token
        - name: XARMOR_BACKEND_URL
          key: xarmor_backend_url
        - name: XARMOR_TENANT_ID
          key: xarmor_tenant_id
        - name: DATA_STORAGE_LOCATION
          key: DATA_STORAGE_LOCATION
        - name: DATA_STORAGE_COMMUNITY
          key: DATA_STORAGE_COMMUNITY
    plainValues:
      - name: PRIVACY_LINK
        value: https://mindspore.cn/privacy/en/
      - name: CONDUCT_LINK
        value: https://gitee.com/mindspore/community/blob/master/code-of-conduct_en.md
      - name: MAILMAN_ADMIN_USER
        value: mindspore
  resources:
    limits:
      cpu: "2"
      memory: 4000Mi
    requests:
      cpu: "1"
      memory: 2000Mi
  service:
    name: mailman-web-service
    type: ClusterIP
    ports:
      - port: 8000
        name: website-port-uwsgi-http
        targetPort: 8000
        protocol: TCP
      - port: 80
        name: website-port-http
        targetPort: 80
        protocol: TCP
    portNumber: 80
nginxWeb:
  image:
    repository: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/nginx
    tag: latest
    imagePullPolicy: IfNotPresent
  resources:
    limits:
      cpu: "1"
      memory: 1Gi
    requests:
      cpu: "1"
      memory: 1Gi
  configmapName: mailman-nginx-configmap
tls:
  secrets:
    - name: mailman-tls-secrets
      path: secrets/data/mindspore/mail_secrets
      keysMap:
        mindspore_cn_crt: mindspore_cn_crt
        mindspore_cn_key: mindspore_cn_key
    - name: mailman-cert-secrets
      path: secrets/data/mindspore/website-secrets
      keysMap:
        server_crt: server.crt
        server_key: server.key
mailwebSecrets:
  name: mailman-secrets
  path: secrets/data/mindspore/mail_secrets
  keysMap:
    hyperkitty_api_key: hyperkitty_api_key
    mailman_core_password: mailman_core_password
    mailman_core_user: mailman_core_user
    secret_key: secret_key
    postgres_user: postgres_user
    postgres_password: postgres_password
    mailman_admin_email: mailman_admin_email
    exim4_credential: exim4_credential
    exim4_credential_username: exim4_credential_splitted_username
    exim4_credential_password: exim4_credential_splitted_password
    dkim_key: dkim_key
    mailweb_smtp_host: mailweb_smtp_host
    mailweb_smtp_port: mailweb_smtp_port
    mailweb_django_allowed_hosts: mailweb_django_allowed_hosts
    mailweb_postorius_template_base_url: mailweb_postorius_template_base_url
    mailweb_database_url: mailweb_database_url
    mailweb_server_from_domain: mailweb_server_from_domain
    mailweb_server_web_domain: mailweb_server_web_domain
    mailcore_mm_hostname: mailcore_mm_hostname
    mailcore_rest_port: mailcore_rest_port
    mailcore_database_url: mailweb_database_url
    mailcore_mta: mailcore_mta
    mailcore_smtp_port: mailweb_smtp_port
    database_type: database_type
    database_class: database_class
    mailman-api-url: mailman_api_url
    mailweb_redis_ip: mailweb_redis_ip
    mailweb_redis_port: mailweb_redis_port
    mailweb_redis_password: mailweb_redis_password
    xarmor_app_id: xarmor_app_id
    xarmor_app_token: xarmor_app_token
    xarmor_backend_url: xarmor_backend_url
    xarmor_tenant_id: xarmor_tenant_id
    DATA_STORAGE_LOCATION: DATA_STORAGE_LOCATION
    DATA_STORAGE_COMMUNITY: DATA_STORAGE_COMMUNITY
cronjob:
  enabled: true
  name: scan-subscribe-pending-cronjob
  schedule: "0 0 * * *"
  concurrencyPolicy: Forbid
  restartPolicy: OnFailure
  image:
    repository: swr.cn-north-4.myhuaweicloud.com/opensourceway/app-mailman/clean-pending-subscription
    tag: 4a229e7f654a4ba58ca0df6c84d81ed0e011ab701702451209
  resources:
    limits:
      cpu: 1000m
      memory: 1000Mi
    requests:
      cpu: 500m
      memory: 500Mi
  env:
    secretRef:
      keys:
        - name: mailman_url
          key: mailman-api-url
        - name: mailman_username
          key: mailman_core_user
        - name: mailman_password
          key: mailman_core_password
