apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.statement.name }}-deployment
  labels:
    {{- include "unifiedbus.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.statement.replicaCount }}
  {{- with .Values.updateStrategy }}
  strategy: 
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- with .Values.statement.podLabels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  template:
    metadata:
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- toYaml .Values.statement.podAnnotations | nindent 8 }}
      labels:
        {{- with .Values.statement.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.statement.name }}
          {{- with .Values.statement.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.statement.image.repository }}:{{ .Values.statement.image.tag }}"
          imagePullPolicy: {{ .Values.statement.image.pullPolicy }}
          {{- with .Values.statement.args }}
          args:
          {{- toYaml . | nindent 12}}
          {{- end }}
          {{- with .Values.statement.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.statement.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.statement.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.statement.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.statement.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
