apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.appName }}-service
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - name: {{ .Values.backend.service.portName }}
    port: {{ .Values.backend.service.port }}
    protocol: TCP
    targetPort: {{ .Values.backend.service.targetPort }}
  selector:
    {{- toYaml .Values.backend.podLabels | nindent 4 }}
  type: {{ .Values.backend.service.type }}
