{{- range .Values.secrets }}
---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  name: {{ .name }}
  keysMap:
    ca.crt:
      key: {{ .certKey }}
      path: {{ .path }}
    tls.crt:
      key: {{ .certKey }}
      path: {{ .path }}
    tls.key:
      key: {{ .keyKey }}
      path: {{ .path }}
{{- end }}
